export const expectedExtensions = [
  "./src/extensions/sandbox/index.ts",
  "./src/extensions/readonly/index.ts",
  "./src/extensions/context/index.ts",
  "./src/extensions/ui/index.ts",
  "./src/extensions/personality/index.ts",
  "./src/extensions/guidance/index.ts",
  "./src/extensions/lsp/index.ts",
  "./src/extensions/processes/index.ts",
  "./src/extensions/subagents/index.ts",
  "./src/extensions/implement/index.ts",
  "./src/extensions/web/index.ts",
  "./src/extensions/browser/index.ts",
  "./src/extensions/papercuts/index.ts",
  "./src/extensions/btw/index.ts",
];
export const expectedTools = {
  output_list: "context",
  read_output: "context",
  lsp_definition: "lsp",
  lsp_type_definition: "lsp",
  lsp_implementation: "lsp",
  lsp_references: "lsp",
  lsp_hover: "lsp",
  lsp_document_symbols: "lsp",
  lsp_workspace_symbols: "lsp",
  lsp_diagnostics: "lsp",
  lsp_status: "lsp",
  process_start: "processes",
  process_list: "processes",
  process_inspect: "processes",
  process_wait: "processes",
  process_stop: "processes",
  agent_start: "subagents",
  agent_wait: "subagents",
  agent_list: "subagents",
  agent_inspect: "subagents",
  agent_stop: "subagents",
  agent_steer: "subagents",
  inspect_implement_run: "implement",
  web_fetch: "web",
  browser_snapshot: "browser",
  browser_screenshot: "browser",
  browser_text: "browser",
  browser_element: "browser",
  browser_diagnostics: "browser",
  browser_tabs: "browser",
  browser_navigate: "browser",
  browser_history: "browser",
  browser_click: "browser",
  browser_hover: "browser",
  browser_set_checked: "browser",
  browser_fill: "browser",
  browser_type: "browser",
  browser_press: "browser",
  browser_select: "browser",
  browser_scroll: "browser",
  browser_wait: "browser",
  browser_viewport: "browser",
  browser_open_tab: "browser",
  browser_switch_tab: "browser",
  browser_close_tab: "browser",
  inspect_papercuts: "papercuts",
  record_papercut: "papercuts",
};
export const expectedCommands = {
  sandbox: "sandbox",
  readonly: "readonly",
  processes: "processes",
  agents: "subagents",
  implement: "implement",
  papercuts: "papercuts",
  btw: "btw",
};
export const privateExposures = {
  explore: "deferred",
  pi_managed_complete: "model-only",
} as const;
